# Generated by Django 5.1.4 on 2025-05-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipe',
            new_name='recipees',
        ),
    ]
