# Generated by Django 5.1.4 on 2025-05-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_rename_recipe_recipees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipees',
            name='recipe_image',
            field=models.ImageField(upload_to='recipes/'),
        ),
    ]
